//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 11:59:42 AM CST 
//


package com.baiwang.einvoice.qz.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
  * @ClassName: Business
  * @Description: 封装无忧报文的实体对象
  * @author zhaowei
  * @date 2016年3月14日 下午4:17:49
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customData",
    "requestcommonfpkj"
})
@XmlRootElement(name = "business")
public class Business {

    @XmlElement(name = "CUSTOMDATA", required = true)
    protected CustomData customData;
    @XmlElement(name = "REQUEST_COMMON_FPKJ", required = true)
    protected RequestCommonFpkj requestcommonfpkj;
    @XmlAttribute(name = "id")
    protected String id;

    
	public CustomData getCustomData() {
	
		return customData;
	}


	public void setCustomData(CustomData customData) {
	
		this.customData = customData;
	}


	public RequestCommonFpkj getRequestcommonfpkj() {
	
		return requestcommonfpkj;
	}


	public void setRequestcommonfpkj(RequestCommonFpkj requestcommonfpkj) {
	
		this.requestcommonfpkj = requestcommonfpkj;
	}


	public RequestCommonFpkj getREQUESTCOMMONFPKJ() {
        return requestcommonfpkj;
    }

   
    public void setREQUESTCOMMONFPKJ(RequestCommonFpkj value) {
        this.requestcommonfpkj = value;
    }

 
    public String getId() {
        return id;
    }

   
    public void setId(String value) {
        this.id = value;
    }

}
