//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 12:39:11 PM CST 
//


package com.baiwang.einvoice.qz.beans;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="REQUEST_COMMON_FPKJ">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="COMMON_FPKJ_FPT">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="FPQQLSH" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="XTBS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="JHKEY" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="KPLX" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="XSF_NSRSBH" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="XSF_MC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="XSF_DZDH" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="XSF_YHZH" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="GMF_NSRSBH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="GMF_MC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="GMF_DZDH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="GMF_YHZH" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="GMF_YX" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="GMF_SJH" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="KPR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SKR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="FHR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="YFP_DM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="YFP_HM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="JSHJ" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="HJJE" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="HJSE" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="BZ" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="expand">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="COMMON_FPKJ_XMXXS">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="COMMON_FPKJ_XMXX" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="FPHXZ" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="XMMC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="GGXH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="DW" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="XMSL" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="XMDJ" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="XMJE" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="SL" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="SE" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestcommonfpkj"
})
@XmlRootElement(name = "business")
public class Business {

    @XmlElement(name = "REQUEST_COMMON_FPKJ", required = true)
    protected Business.REQUESTCOMMONFPKJ requestcommonfpkj;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "comment")
    protected String comment;

    /**
     * Gets the value of the requestcommonfpkj property.
     * 
     * @return
     *     possible object is
     *     {@link Business.REQUESTCOMMONFPKJ }
     *     
     */
    public Business.REQUESTCOMMONFPKJ getREQUESTCOMMONFPKJ() {
        return requestcommonfpkj;
    }

    /**
     * Sets the value of the requestcommonfpkj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Business.REQUESTCOMMONFPKJ }
     *     
     */
    public void setREQUESTCOMMONFPKJ(Business.REQUESTCOMMONFPKJ value) {
        this.requestcommonfpkj = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="COMMON_FPKJ_FPT">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="FPQQLSH" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="XTBS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="JHKEY" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="KPLX" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="XSF_NSRSBH" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="XSF_MC" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="XSF_DZDH" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="XSF_YHZH" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="GMF_NSRSBH" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="GMF_MC" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="GMF_DZDH" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="GMF_YHZH" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="GMF_YX" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="GMF_SJH" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="KPR" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SKR" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="FHR" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="YFP_DM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="YFP_HM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="JSHJ" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="HJJE" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="HJSE" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="BZ" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="expand">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="COMMON_FPKJ_XMXXS">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="COMMON_FPKJ_XMXX" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="FPHXZ" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="XMMC" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="GGXH" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="DW" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="XMSL" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="XMDJ" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="XMJE" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="SL" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="SE" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "commonfpkjfpt",
        "commonfpkjxmxxs"
    })
    public static class REQUESTCOMMONFPKJ {

        @XmlElement(name = "COMMON_FPKJ_FPT", required = true)
        protected Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT commonfpkjfpt;
        @XmlElement(name = "COMMON_FPKJ_XMXXS", required = true)
        protected Business.REQUESTCOMMONFPKJ.COMMONFPKJXMXXS commonfpkjxmxxs;
        @XmlAttribute(name = "class")
        protected String clazz;

        /**
         * Gets the value of the commonfpkjfpt property.
         * 
         * @return
         *     possible object is
         *     {@link Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT }
         *     
         */
        public Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT getCOMMONFPKJFPT() {
            return commonfpkjfpt;
        }

        /**
         * Sets the value of the commonfpkjfpt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT }
         *     
         */
        public void setCOMMONFPKJFPT(Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT value) {
            this.commonfpkjfpt = value;
        }

        /**
         * Gets the value of the commonfpkjxmxxs property.
         * 
         * @return
         *     possible object is
         *     {@link Business.REQUESTCOMMONFPKJ.COMMONFPKJXMXXS }
         *     
         */
        public Business.REQUESTCOMMONFPKJ.COMMONFPKJXMXXS getCOMMONFPKJXMXXS() {
            return commonfpkjxmxxs;
        }

        /**
         * Sets the value of the commonfpkjxmxxs property.
         * 
         * @param value
         *     allowed object is
         *     {@link Business.REQUESTCOMMONFPKJ.COMMONFPKJXMXXS }
         *     
         */
        public void setCOMMONFPKJXMXXS(Business.REQUESTCOMMONFPKJ.COMMONFPKJXMXXS value) {
            this.commonfpkjxmxxs = value;
        }

        /**
         * Gets the value of the clazz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClazz(String value) {
            this.clazz = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="FPQQLSH" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="XTBS" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="JHKEY" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="KPLX" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="XSF_NSRSBH" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="XSF_MC" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="XSF_DZDH" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="XSF_YHZH" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="GMF_NSRSBH" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="GMF_MC" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="GMF_DZDH" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="GMF_YHZH" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="GMF_YX" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="GMF_SJH" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="KPR" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SKR" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="FHR" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="YFP_DM" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="YFP_HM" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="JSHJ" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="HJJE" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="HJSE" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="BZ" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="expand">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fpqqlsh",
            "xtbs",
            "jhkey",
            "kplx",
            "xsfnsrsbh",
            "xsfmc",
            "xsfdzdh",
            "xsfyhzh",
            "gmfnsrsbh",
            "gmfmc",
            "gmfdzdh",
            "gmfyhzh",
            "gmfyx",
            "gmfsjh",
            "kpr",
            "skr",
            "fhr",
            "yfpdm",
            "yfphm",
            "jshj",
            "hjje",
            "hjse",
            "bz",
            "expand"
        })
        public static class COMMONFPKJFPT {

            @XmlElement(name = "FPQQLSH", required = true)
            protected BigInteger fpqqlsh;
            @XmlElement(name = "XTBS", required = true)
            protected String xtbs;
            @XmlElement(name = "JHKEY")
            protected int jhkey;
            @XmlElement(name = "KPLX")
            protected byte kplx;
            @XmlElement(name = "XSF_NSRSBH")
            protected long xsfnsrsbh;
            @XmlElement(name = "XSF_MC", required = true)
            protected String xsfmc;
            @XmlElement(name = "XSF_DZDH")
            protected long xsfdzdh;
            @XmlElement(name = "XSF_YHZH")
            protected long xsfyhzh;
            @XmlElement(name = "GMF_NSRSBH", required = true)
            protected String gmfnsrsbh;
            @XmlElement(name = "GMF_MC", required = true)
            protected String gmfmc;
            @XmlElement(name = "GMF_DZDH", required = true)
            protected String gmfdzdh;
            @XmlElement(name = "GMF_YHZH")
            protected long gmfyhzh;
            @XmlElement(name = "GMF_YX", required = true)
            protected String gmfyx;
            @XmlElement(name = "GMF_SJH")
            protected long gmfsjh;
            @XmlElement(name = "KPR", required = true)
            protected String kpr;
            @XmlElement(name = "SKR", required = true)
            protected String skr;
            @XmlElement(name = "FHR", required = true)
            protected String fhr;
            @XmlElement(name = "YFP_DM", required = true)
            protected String yfpdm;
            @XmlElement(name = "YFP_HM", required = true)
            protected String yfphm;
            @XmlElement(name = "JSHJ")
            protected float jshj;
            @XmlElement(name = "HJJE")
            protected float hjje;
            @XmlElement(name = "HJSE")
            protected float hjse;
            @XmlElement(name = "BZ", required = true)
            protected String bz;
            @XmlElement(required = true)
            protected Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT.Expand expand;
            @XmlAttribute(name = "class")
            protected String clazz;

            /**
             * Gets the value of the fpqqlsh property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getFPQQLSH() {
                return fpqqlsh;
            }

            /**
             * Sets the value of the fpqqlsh property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setFPQQLSH(BigInteger value) {
                this.fpqqlsh = value;
            }

            /**
             * Gets the value of the xtbs property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getXTBS() {
                return xtbs;
            }

            /**
             * Sets the value of the xtbs property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setXTBS(String value) {
                this.xtbs = value;
            }

            /**
             * Gets the value of the jhkey property.
             * 
             */
            public int getJHKEY() {
                return jhkey;
            }

            /**
             * Sets the value of the jhkey property.
             * 
             */
            public void setJHKEY(int value) {
                this.jhkey = value;
            }

            /**
             * Gets the value of the kplx property.
             * 
             */
            public byte getKPLX() {
                return kplx;
            }

            /**
             * Sets the value of the kplx property.
             * 
             */
            public void setKPLX(byte value) {
                this.kplx = value;
            }

            /**
             * Gets the value of the xsfnsrsbh property.
             * 
             */
            public long getXSFNSRSBH() {
                return xsfnsrsbh;
            }

            /**
             * Sets the value of the xsfnsrsbh property.
             * 
             */
            public void setXSFNSRSBH(long value) {
                this.xsfnsrsbh = value;
            }

            /**
             * Gets the value of the xsfmc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getXSFMC() {
                return xsfmc;
            }

            /**
             * Sets the value of the xsfmc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setXSFMC(String value) {
                this.xsfmc = value;
            }

            /**
             * Gets the value of the xsfdzdh property.
             * 
             */
            public long getXSFDZDH() {
                return xsfdzdh;
            }

            /**
             * Sets the value of the xsfdzdh property.
             * 
             */
            public void setXSFDZDH(long value) {
                this.xsfdzdh = value;
            }

            /**
             * Gets the value of the xsfyhzh property.
             * 
             */
            public long getXSFYHZH() {
                return xsfyhzh;
            }

            /**
             * Sets the value of the xsfyhzh property.
             * 
             */
            public void setXSFYHZH(long value) {
                this.xsfyhzh = value;
            }

            /**
             * Gets the value of the gmfnsrsbh property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGMFNSRSBH() {
                return gmfnsrsbh;
            }

            /**
             * Sets the value of the gmfnsrsbh property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGMFNSRSBH(String value) {
                this.gmfnsrsbh = value;
            }

            /**
             * Gets the value of the gmfmc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGMFMC() {
                return gmfmc;
            }

            /**
             * Sets the value of the gmfmc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGMFMC(String value) {
                this.gmfmc = value;
            }

            /**
             * Gets the value of the gmfdzdh property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGMFDZDH() {
                return gmfdzdh;
            }

            /**
             * Sets the value of the gmfdzdh property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGMFDZDH(String value) {
                this.gmfdzdh = value;
            }

            /**
             * Gets the value of the gmfyhzh property.
             * 
             */
            public long getGMFYHZH() {
                return gmfyhzh;
            }

            /**
             * Sets the value of the gmfyhzh property.
             * 
             */
            public void setGMFYHZH(long value) {
                this.gmfyhzh = value;
            }

            /**
             * Gets the value of the gmfyx property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGMFYX() {
                return gmfyx;
            }

            /**
             * Sets the value of the gmfyx property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGMFYX(String value) {
                this.gmfyx = value;
            }

            /**
             * Gets the value of the gmfsjh property.
             * 
             */
            public long getGMFSJH() {
                return gmfsjh;
            }

            /**
             * Sets the value of the gmfsjh property.
             * 
             */
            public void setGMFSJH(long value) {
                this.gmfsjh = value;
            }

            /**
             * Gets the value of the kpr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKPR() {
                return kpr;
            }

            /**
             * Sets the value of the kpr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKPR(String value) {
                this.kpr = value;
            }

            /**
             * Gets the value of the skr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSKR() {
                return skr;
            }

            /**
             * Sets the value of the skr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSKR(String value) {
                this.skr = value;
            }

            /**
             * Gets the value of the fhr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFHR() {
                return fhr;
            }

            /**
             * Sets the value of the fhr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFHR(String value) {
                this.fhr = value;
            }

            /**
             * Gets the value of the yfpdm property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getYFPDM() {
                return yfpdm;
            }

            /**
             * Sets the value of the yfpdm property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setYFPDM(String value) {
                this.yfpdm = value;
            }

            /**
             * Gets the value of the yfphm property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getYFPHM() {
                return yfphm;
            }

            /**
             * Sets the value of the yfphm property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setYFPHM(String value) {
                this.yfphm = value;
            }

            /**
             * Gets the value of the jshj property.
             * 
             */
            public float getJSHJ() {
                return jshj;
            }

            /**
             * Sets the value of the jshj property.
             * 
             */
            public void setJSHJ(float value) {
                this.jshj = value;
            }

            /**
             * Gets the value of the hjje property.
             * 
             */
            public float getHJJE() {
                return hjje;
            }

            /**
             * Sets the value of the hjje property.
             * 
             */
            public void setHJJE(float value) {
                this.hjje = value;
            }

            /**
             * Gets the value of the hjse property.
             * 
             */
            public float getHJSE() {
                return hjse;
            }

            /**
             * Sets the value of the hjse property.
             * 
             */
            public void setHJSE(float value) {
                this.hjse = value;
            }

            /**
             * Gets the value of the bz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBZ() {
                return bz;
            }

            /**
             * Sets the value of the bz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBZ(String value) {
                this.bz = value;
            }

            /**
             * Gets the value of the expand property.
             * 
             * @return
             *     possible object is
             *     {@link Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT.Expand }
             *     
             */
            public Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT.Expand getExpand() {
                return expand;
            }

            /**
             * Sets the value of the expand property.
             * 
             * @param value
             *     allowed object is
             *     {@link Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT.Expand }
             *     
             */
            public void setExpand(Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT.Expand value) {
                this.expand = value;
            }

            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClazz() {
                return clazz;
            }

            /**
             * Sets the value of the clazz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClazz(String value) {
                this.clazz = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name",
                "value"
            })
            public static class Expand {

                @XmlElement(required = true)
                protected String name;
                @XmlElement(required = true)
                protected String value;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="COMMON_FPKJ_XMXX" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="FPHXZ" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="XMMC" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="GGXH" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="DW" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="XMSL" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="XMDJ" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="XMJE" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="SL" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="SE" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "commonfpkjxmxx"
        })
        public static class COMMONFPKJXMXXS {

            @XmlElement(name = "COMMON_FPKJ_XMXX")
            protected List<Business.REQUESTCOMMONFPKJ.COMMONFPKJXMXXS.COMMONFPKJXMXX> commonfpkjxmxx;
            @XmlAttribute(name = "class")
            protected String clazz;
            @XmlAttribute(name = "size")
            protected Byte size;

            /**
             * Gets the value of the commonfpkjxmxx property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the commonfpkjxmxx property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCOMMONFPKJXMXX().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Business.REQUESTCOMMONFPKJ.COMMONFPKJXMXXS.COMMONFPKJXMXX }
             * 
             * 
             */
            public List<Business.REQUESTCOMMONFPKJ.COMMONFPKJXMXXS.COMMONFPKJXMXX> getCOMMONFPKJXMXX() {
                if (commonfpkjxmxx == null) {
                    commonfpkjxmxx = new ArrayList<Business.REQUESTCOMMONFPKJ.COMMONFPKJXMXXS.COMMONFPKJXMXX>();
                }
                return this.commonfpkjxmxx;
            }

            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClazz() {
                return clazz;
            }

            /**
             * Sets the value of the clazz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClazz(String value) {
                this.clazz = value;
            }

            /**
             * Gets the value of the size property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getSize() {
                return size;
            }

            /**
             * Sets the value of the size property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setSize(Byte value) {
                this.size = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="FPHXZ" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="XMMC" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="GGXH" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="DW" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="XMSL" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="XMDJ" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="XMJE" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="SL" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="SE" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "fphxz",
                "xmmc",
                "ggxh",
                "dw",
                "xmsl",
                "xmdj",
                "xmje",
                "sl",
                "se"
            })
            public static class COMMONFPKJXMXX {

                @XmlElement(name = "FPHXZ")
                protected byte fphxz;
                @XmlElement(name = "XMMC", required = true)
                protected String xmmc;
                @XmlElement(name = "GGXH", required = true)
                protected String ggxh;
                @XmlElement(name = "DW", required = true)
                protected String dw;
                @XmlElement(name = "XMSL")
                protected byte xmsl;
                @XmlElement(name = "XMDJ")
                protected byte xmdj;
                @XmlElement(name = "XMJE")
                protected float xmje;
                @XmlElement(name = "SL")
                protected float sl;
                @XmlElement(name = "SE")
                protected float se;

                /**
                 * Gets the value of the fphxz property.
                 * 
                 */
                public byte getFPHXZ() {
                    return fphxz;
                }

                /**
                 * Sets the value of the fphxz property.
                 * 
                 */
                public void setFPHXZ(byte value) {
                    this.fphxz = value;
                }

                /**
                 * Gets the value of the xmmc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getXMMC() {
                    return xmmc;
                }

                /**
                 * Sets the value of the xmmc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setXMMC(String value) {
                    this.xmmc = value;
                }

                /**
                 * Gets the value of the ggxh property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGGXH() {
                    return ggxh;
                }

                /**
                 * Sets the value of the ggxh property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGGXH(String value) {
                    this.ggxh = value;
                }

                /**
                 * Gets the value of the dw property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDW() {
                    return dw;
                }

                /**
                 * Sets the value of the dw property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDW(String value) {
                    this.dw = value;
                }

                /**
                 * Gets the value of the xmsl property.
                 * 
                 */
                public byte getXMSL() {
                    return xmsl;
                }

                /**
                 * Sets the value of the xmsl property.
                 * 
                 */
                public void setXMSL(byte value) {
                    this.xmsl = value;
                }

                /**
                 * Gets the value of the xmdj property.
                 * 
                 */
                public byte getXMDJ() {
                    return xmdj;
                }

                /**
                 * Sets the value of the xmdj property.
                 * 
                 */
                public void setXMDJ(byte value) {
                    this.xmdj = value;
                }

                /**
                 * Gets the value of the xmje property.
                 * 
                 */
                public float getXMJE() {
                    return xmje;
                }

                /**
                 * Sets the value of the xmje property.
                 * 
                 */
                public void setXMJE(float value) {
                    this.xmje = value;
                }

                /**
                 * Gets the value of the sl property.
                 * 
                 */
                public float getSL() {
                    return sl;
                }

                /**
                 * Sets the value of the sl property.
                 * 
                 */
                public void setSL(float value) {
                    this.sl = value;
                }

                /**
                 * Gets the value of the se property.
                 * 
                 */
                public float getSE() {
                    return se;
                }

                /**
                 * Sets the value of the se property.
                 * 
                 */
                public void setSE(float value) {
                    this.se = value;
                }

            }

        }

    }

}
