//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 12:39:11 PM CST 
//


package com.baiwang.einvoice.qz.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.baiwang.einvoice.qz.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.baiwang.einvoice.qz.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Business }
     * 
     */
    public Business createBusiness() {
        return new Business();
    }

    /**
     * Create an instance of {@link Business.REQUESTCOMMONFPKJ }
     * 
     */
    public Business.REQUESTCOMMONFPKJ createBusinessREQUESTCOMMONFPKJ() {
        return new Business.REQUESTCOMMONFPKJ();
    }

    /**
     * Create an instance of {@link Business.REQUESTCOMMONFPKJ.COMMONFPKJXMXXS }
     * 
     */
    public Business.REQUESTCOMMONFPKJ.COMMONFPKJXMXXS createBusinessREQUESTCOMMONFPKJCOMMONFPKJXMXXS() {
        return new Business.REQUESTCOMMONFPKJ.COMMONFPKJXMXXS();
    }

    /**
     * Create an instance of {@link Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT }
     * 
     */
    public Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT createBusinessREQUESTCOMMONFPKJCOMMONFPKJFPT() {
        return new Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT();
    }

    /**
     * Create an instance of {@link Business.REQUESTCOMMONFPKJ.COMMONFPKJXMXXS.COMMONFPKJXMXX }
     * 
     */
    public Business.REQUESTCOMMONFPKJ.COMMONFPKJXMXXS.COMMONFPKJXMXX createBusinessREQUESTCOMMONFPKJCOMMONFPKJXMXXSCOMMONFPKJXMXX() {
        return new Business.REQUESTCOMMONFPKJ.COMMONFPKJXMXXS.COMMONFPKJXMXX();
    }

    /**
     * Create an instance of {@link Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT.Expand }
     * 
     */
    public Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT.Expand createBusinessREQUESTCOMMONFPKJCOMMONFPKJFPTExpand() {
        return new Business.REQUESTCOMMONFPKJ.COMMONFPKJFPT.Expand();
    }

}
